import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { api } from '../lib/apiClient';
import type { ArtisanFinancialSummary, BomItem, JobOffer, ProductionJob } from '@sbdmm/shared';

type Tab='offers'|'jobs'|'bom'|'financials';
const money=(value:number,currency='ZAR')=>new Intl.NumberFormat('en-ZA',{style:'currency',currency}).format(value);

function Countdown({expiresAt,onExpired}:{expiresAt:string;onExpired:()=>void}):React.JSX.Element{
  const [seconds,setSeconds]=useState(()=>Math.max(0,Math.floor((new Date(expiresAt).getTime()-Date.now())/1000)));
  useEffect(()=>{const timer=window.setInterval(()=>setSeconds(current=>{if(current<=1){window.clearInterval(timer);onExpired();return 0;}return current-1;}),1000);return()=>window.clearInterval(timer);},[expiresAt,onExpired]);
  return <strong style={{color:seconds<120?'#b91c1c':'#0f766e'}}>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</strong>;
}

function BomEditor({job,onSaved}:{job:ProductionJob;onSaved:()=>void}):React.JSX.Element{
  const latest=useMemo(()=>[...(job.bom_versions??[])].sort((a,b)=>b.version-a.version)[0],[job.bom_versions]);
  const [items,setItems]=useState<BomItem[]>(latest?.bom_items??[]);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
  useEffect(()=>setItems(latest?.bom_items??[]),[latest]);
  const update=(index:number,key:keyof BomItem,value:unknown)=>setItems(current=>current.map((row,i)=>i===index?{...row,[key]:value}:row));
  const save=async()=>{if(!latest)return;setSaving(true);setError('');const result=await api.post(`/api/v1/production/jobs/${job.id}/bom`,{assumptions:latest.assumptions??[],unresolved_questions:latest.unresolved_questions??[],estimated_labour_hours:latest.estimated_labour_hours??0,estimated_machine_hours:latest.estimated_machine_hours??0,estimated_production_days:latest.estimated_production_days??1,currency:latest.currency,items:items.map(({id:_,...row})=>row)});setSaving(false);if(!result.success){setError(result.error?.message??'Unable to save BOM.');return;}onSaved();};
  if(!latest)return <div className="alert alert-warning">The AI draft BOM is not available yet.</div>;
  return <section className="card border-0 shadow-sm"><div className="card-body p-24">
    <div className="d-flex justify-content-between align-items-start mb-16"><div><h3 className="h5 mb-4">Bill of Materials v{latest.version}</h3><p className="text-muted mb-0">{latest.source==='openai'?'AI-generated draft — validate every line before procurement or payment.':'Artisan revision'}</p></div><span className="badge text-bg-warning">{latest.status.replace('_',' ')}</span></div>
    {error&&<div className="alert alert-danger">{error}</div>}
    <div className="table-responsive"><table className="table align-middle"><thead><tr><th>Assembly / item</th><th>Specification</th><th style={{width:90}}>Qty</th><th style={{width:90}}>Unit</th><th style={{width:120}}>Waste %</th><th style={{width:150}}>Est. cost</th></tr></thead><tbody>{items.map((row,index)=><tr key={row.id??`${row.assembly_name}-${index}`}><td><small className="text-muted d-block">{row.assembly_name}</small><input className="form-control" value={row.description} onChange={e=>update(index,'description',e.target.value)}/></td><td><input className="form-control" value={row.specification} onChange={e=>update(index,'specification',e.target.value)}/></td><td><input className="form-control" type="number" min="0.001" step="0.001" value={row.quantity} onChange={e=>update(index,'quantity',Number(e.target.value))}/></td><td><input className="form-control" value={row.unit} onChange={e=>update(index,'unit',e.target.value)}/></td><td><input className="form-control" type="number" min="0" max="100" value={row.waste_percentage} onChange={e=>update(index,'waste_percentage',Number(e.target.value))}/></td><td><input className="form-control" type="number" min="0" value={row.estimated_total_cost??0} onChange={e=>update(index,'estimated_total_cost',Number(e.target.value))}/></td></tr>)}</tbody></table></div>
    <div className="d-flex justify-content-end"><button className="btn btn-primary" disabled={saving} onClick={()=>void save()}>{saving?'Saving…':'Save as new BOM version'}</button></div>
  </div></section>;
}

export default function ArtisanWorkspacePage():React.JSX.Element{
  const [tab,setTab]=useState<Tab>('offers');const [offers,setOffers]=useState<JobOffer[]>([]);const [jobs,setJobs]=useState<ProductionJob[]>([]);const [selected,setSelected]=useState<ProductionJob|null>(null);const [financials,setFinancials]=useState<ArtisanFinancialSummary|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  const [financialJobId,setFinancialJobId]=useState('');const [financialEvent,setFinancialEvent]=useState('material_purchase');const [financialAmount,setFinancialAmount]=useState(0);
  const load=useCallback(async()=>{setLoading(true);const [offerRes,jobRes,financialRes]=await Promise.all([api.get<JobOffer[]>('/api/v1/production/offers/me'),api.get<ProductionJob[]>('/api/v1/production/jobs'),api.get<ArtisanFinancialSummary>('/api/v1/production/financials/summary')]);setLoading(false);if(offerRes.success)setOffers(offerRes.data??[]);if(jobRes.success)setJobs(jobRes.data??[]);if(financialRes.success)setFinancials(financialRes.data??null);},[]);
  useEffect(()=>{void load();},[load]);
  const openJob=async(job:ProductionJob)=>{const result=await api.get<ProductionJob>(`/api/v1/production/jobs/${job.id}`);if(result.success&&result.data){setSelected(result.data);setTab('bom');}};
  const offerAction=async(offer:JobOffer,action:'accept'|'decline')=>{setError('');const result=await api.post(`/api/v1/production/offers/${offer.id}/${action}`,action==='decline'?{reason:'Not available for this production window'}:{});if(!result.success){setError(result.error?.message??'Unable to update offer.');return;}await load();if(action==='accept')setTab('jobs');};
  const confirmJob=async(job:ProductionJob)=>{const bom=[...(selected?.bom_versions??[])].sort((a,b)=>b.version-a.version)[0];if(!bom)return;const price=Number(window.prompt('Confirm final job price',String(job.final_job_price??bom.subtotal_materials)));const date=window.prompt('Estimated completion date (YYYY-MM-DD)',job.estimated_completion_date??'');if(!price||!date)return;const result=await api.post(`/api/v1/production/jobs/${job.id}/confirm`,{bom_version_id:bom.id,final_job_price:price,estimated_completion_date:date});if(!result.success)setError(result.error?.message??'Unable to confirm job.');else await openJob(job);};
  const chooseSourcing=async(method:'artisan_self_procure'|'vendor_procurement')=>{if(!selected)return;const bom=[...(selected.bom_versions??[])].find(v=>v.status==='confirmed')??[...(selected.bom_versions??[])].sort((a,b)=>b.version-a.version)[0];if(!bom)return;const result=await api.post(`/api/v1/production/jobs/${selected.id}/sourcing`,{bom_version_id:bom.id,method,material_budget:bom.subtotal_materials,...(method==='artisan_self_procure'?{funding_method:'included_in_job_price'}:{})});if(!result.success)setError(result.error?.message??'Unable to save sourcing choice.');else await openJob(selected);};
  const recordFinancial=async()=>{if(!financialJobId||financialAmount<=0)return;const result=await api.post(`/api/v1/production/jobs/${financialJobId}/financial-events`,{event_type:financialEvent,amount:financialAmount,currency:'ZAR'});if(!result.success)setError(result.error?.message??'Unable to record financial event.');else{setFinancialAmount(0);await load();}};
  return <div className="container-fluid py-24"><div className="d-flex flex-wrap justify-content-between align-items-center gap-12 mb-24"><div><h1 className="h3 mb-4">Artisan Workshop</h1><p className="text-muted mb-0">Accept matched work, validate AI bills of materials, and manage production finances.</p></div><span className="badge rounded-pill text-bg-dark">Artisan</span></div>
    <nav className="nav nav-pills mb-24">{([['offers','Job Offers'],['jobs','Production Jobs'],['bom','Bill of Materials'],['financials','Financials']] as Array<[Tab,string]>).map(([key,label])=><button key={key} className={`nav-link ${tab===key?'active':''}`} onClick={()=>setTab(key)}>{label}{key==='offers'&&offers.length>0&&<span className="badge text-bg-danger ms-8">{offers.length}</span>}</button>)}</nav>
    {error&&<div className="alert alert-danger">{error}</div>}{loading&&<div className="text-center py-40"><span className="spinner-border"/></div>}
    {!loading&&tab==='offers'&&<div className="row g-16">{offers.length===0?<div className="col-12"><div className="card border-0 shadow-sm"><div className="card-body p-32 text-center"><i className="ph ph-timer fs-2"/><h2 className="h5 mt-12">No active job offers</h2><p className="text-muted mb-0">New matched jobs will appear here for 15 minutes.</p></div></div></div>:offers.map(offer=><div className="col-lg-6" key={offer.id}><div className="card border-0 shadow-sm h-100"><div className="card-body p-24"><div className="d-flex justify-content-between"><span className="badge text-bg-primary">Rank #{offer.ranking_position}</span>{offer.expires_at&&<Countdown expiresAt={offer.expires_at} onExpired={()=>void load()}/>}</div><h2 className="h5 mt-16">Custom furniture production job</h2><p className="text-muted">Review the approved design and AI-estimated scope. Acceptance reserves the job; BOM and final-price confirmation follow.</p><div className="d-flex gap-8"><button className="btn btn-primary flex-grow-1" onClick={()=>void offerAction(offer,'accept')}>Accept job</button><button className="btn btn-outline-secondary" onClick={()=>void offerAction(offer,'decline')}>Decline</button></div></div></div></div>)}</div>}
    {!loading&&tab==='jobs'&&<div className="row g-16">{jobs.map(job=><div className="col-lg-6" key={job.id}><div className="card border-0 shadow-sm"><div className="card-body p-24"><div className="d-flex justify-content-between"><h2 className="h5">Job {job.id.slice(0,8)}</h2><span className="badge text-bg-light">{job.status.replace(/_/g,' ')}</span></div><p className="text-muted">Created {new Date(job.created_at).toLocaleDateString()}</p><button className="btn btn-outline-primary" onClick={()=>void openJob(job)}>Open production job</button></div></div></div>)}</div>}
    {!loading&&tab==='bom'&&(selected?<><BomEditor job={selected} onSaved={()=>void openJob(selected)}/><div className="card border-0 shadow-sm mt-16"><div className="card-body p-24"><h3 className="h5">Final confirmation and sourcing</h3><p className="text-muted">Payments remain blocked until the final job and material route are confirmed.</p><div className="d-flex flex-wrap gap-8"><button className="btn btn-dark" onClick={()=>void confirmJob(selected)}>Confirm final job</button><button className="btn btn-outline-primary" disabled={selected.status!=='confirmed'} onClick={()=>void chooseSourcing('artisan_self_procure')}>I will buy materials</button><button className="btn btn-outline-primary" disabled={selected.status!=='confirmed'} onClick={()=>void chooseSourcing('vendor_procurement')}>Request Vendor quotations</button></div></div></div></>:<div className="alert alert-info">Open a production job to review its BOM.</div>)}
    {!loading&&tab==='financials'&&<><div className="alert alert-warning">{financials?.label??'Draft management report — accountant review required'}</div><div className="row g-16">{financials&&([['Revenue',financials.revenue],['Expenses',financials.expenses],['Profit',financials.profit],['Assets',financials.assets],['Liabilities',financials.liabilities],['Equity',financials.equity]] as Array<[string,number]>).map(([label,value])=><div className="col-md-4" key={label}><div className="card border-0 shadow-sm"><div className="card-body p-24"><small className="text-muted">{label}</small><div className="h4 mt-8 mb-0">{money(value)}</div></div></div></div>)}</div><div className="card border-0 shadow-sm mt-16"><div className="card-body p-24"><h3 className="h5">Record job financial event</h3><p className="text-muted">Creates a balanced, source-linked draft IFRS job-subledger entry. Revenue recognition remains subject to your accounting policy and accountant review.</p><div className="row g-12"><div className="col-md-4"><select className="form-select" value={financialJobId} onChange={e=>setFinancialJobId(e.target.value)}><option value="">Select production job</option>{jobs.map(job=><option value={job.id} key={job.id}>Job {job.id.slice(0,8)}</option>)}</select></div><div className="col-md-4"><select className="form-select" value={financialEvent} onChange={e=>setFinancialEvent(e.target.value)}><option value="material_purchase">Material purchase</option><option value="materials_issued">Materials issued to WIP</option><option value="direct_labour">Direct labour</option><option value="production_completed">Production completed</option><option value="control_transferred">Control transferred / revenue</option><option value="customer_payment">Customer payment</option><option value="vendor_payable">Vendor payable</option></select></div><div className="col-md-2"><input className="form-control" type="number" min="0" value={financialAmount} onChange={e=>setFinancialAmount(Number(e.target.value))}/></div><div className="col-md-2"><button className="btn btn-primary w-100" onClick={()=>void recordFinancial()}>Post event</button></div></div></div></div></>}
  </div>;
}
