import React,{useEffect,useState} from 'react';
import {api} from '../lib/apiClient';
import type {BomItem} from '@sbdmm/shared';

interface SupplyRequest{ id:string;status:string;response_deadline:string;required_by:string|null;bom_versions:{id:string;version:number;currency:string;bom_items:BomItem[]}|null; }

export default function VendorSupplyRequestsPage():React.JSX.Element{
  const [requests,setRequests]=useState<SupplyRequest[]>([]);const [selected,setSelected]=useState<SupplyRequest|null>(null);const [prices,setPrices]=useState<Record<number,number>>({});const [leadTime,setLeadTime]=useState(7);const [error,setError]=useState('');
  const load=async()=>{const result=await api.get<SupplyRequest[]>('/api/v1/production/supply-requests');if(result.success)setRequests(result.data??[]);else setError(result.error?.message??'Unable to load supply requests.');};useEffect(()=>{void load();},[]);
  const quote=async()=>{if(!selected?.bom_versions)return;const items=selected.bom_versions.bom_items;const line_items=items.map((item,index)=>({bom_item_id:item.id,description:item.description,quantity:item.quantity,unit_price:prices[index]??0}));const subtotal=line_items.reduce((sum,line)=>sum+line.quantity*line.unit_price,0);const result=await api.post(`/api/v1/production/supply-requests/${selected.id}/quotes`,{currency:selected.bom_versions.currency,subtotal,tax:subtotal*.15,delivery_fee:0,lead_time_days:leadTime,valid_until:new Date(Date.now()+7*86400000).toISOString(),payment_terms:'Payment within 30 days',line_items});if(!result.success)setError(result.error?.message??'Unable to submit quotation.');else{setSelected(null);await load();}};
  return <div className="container-fluid py-24"><div className="mb-24"><h1 className="h3 mb-4">Supply Requests</h1><p className="text-muted mb-0">Review procurement-safe artisan BOMs and submit material quotations.</p></div>{error&&<div className="alert alert-danger">{error}</div>}
  <div className="row g-16">{requests.map(request=><div className="col-lg-6" key={request.id}><div className="card border-0 shadow-sm"><div className="card-body p-24"><div className="d-flex justify-content-between"><span className="badge text-bg-success">{request.status}</span><small>Due {new Date(request.response_deadline).toLocaleString()}</small></div><h2 className="h5 mt-16">Material request {request.id.slice(0,8)}</h2><p>{request.bom_versions?.bom_items.length??0} BOM lines · Version {request.bom_versions?.version}</p><button className="btn btn-primary" onClick={()=>setSelected(request)}>Build quotation</button></div></div></div>)}</div>
  {selected?.bom_versions&&<div className="modal d-block" style={{background:'rgba(15,23,42,.55)'}} role="dialog" aria-modal="true"><div className="modal-dialog modal-xl modal-dialog-scrollable"><div className="modal-content"><div className="modal-header"><h2 className="modal-title h5">Vendor quotation</h2><button className="btn-close" onClick={()=>setSelected(null)}/></div><div className="modal-body"><div className="table-responsive"><table className="table"><thead><tr><th>Material</th><th>Specification</th><th>Quantity</th><th>Unit price</th></tr></thead><tbody>{selected.bom_versions.bom_items.map((item,index)=><tr key={item.id??index}><td>{item.description}</td><td>{item.specification}</td><td>{item.quantity} {item.unit}</td><td><input className="form-control" type="number" min="0" value={prices[index]??0} onChange={e=>setPrices(current=>({...current,[index]:Number(e.target.value)}))}/></td></tr>)}</tbody></table></div><label className="form-label">Lead time (days)</label><input className="form-control" type="number" min="1" value={leadTime} onChange={e=>setLeadTime(Number(e.target.value))}/></div><div className="modal-footer"><button className="btn btn-outline-secondary" onClick={()=>setSelected(null)}>Cancel</button><button className="btn btn-primary" onClick={()=>void quote()}>Submit quotation</button></div></div></div></div>}
  </div>;
}
